### TEST CONFIGURATION -> NOT PERFECT! ###
version: '3.8'

networks:
  global-network:
    driver: bridge

services:

  ### Application ##################################
  application:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}_application
    restart: unless-stopped
    working_dir: ${APP_DOCUMENT_ROOT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - global-network
  ##################################################

  ### MySql ########################################
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_ROOT}:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    depends_on:
      - application
    networks:
      - global-network
  ##################################################

  ### PhpMyAdmin ###################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: ${PHPMYADMIN_ARBITRARY}
      PMA_HOST: ${PHPMYADMIN_HOST}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - application
    networks:
      - global-network
  ##################################################

  ### Apache #######################################
  apache2:
    image: webdevops/apache:ubuntu-18.04
    container_name: ${APP_NAME}_apache2
    restart: unless-stopped
    environment:
      WEB_DOCUMENT_ROOT: ${APP_DOCUMENT_ROOT}
      WEB_PHP_SOCKET: ${APACHE_PHP_UPSTREAM_CONTAINER}:${APACHE_PHP_UPSTREAM_PORT}
      WEB_PHP_TIMEOUT: ${APACHE_PHP_UPSTREAM_TIMEOUT}
    ports:
      - ${APACHE_HOST_HTTP_PORT}:80
      - ${APACHE_HOST_HTTPS_PORT}:443
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
    depends_on:
      - application
    networks:
      - global-network
  ##################################################